_target_: fish_vocoder.modules.generators.vocos.VocosGenerator
backbone:
  _target_: fish_vocoder.modules.generators.vocos.VocosBackbone
  input_channels: ${model.num_mels}
  depths: [3, 3, 9, 3]
  dims: [128, 256, 384, 512]
  drop_path_rate: 0.2
  kernel_sizes: [7]
head:
  _target_: fish_vocoder.modules.generators.hifigan.HiFiGANGenerator
  hop_length: ${model.hop_length}
  upsample_rates: [4, 4, 2, 2, 2, 2, 2]  # aka. strides
  upsample_kernel_sizes: [8, 8, 4, 4, 4, 4, 4]
  resblock_kernel_sizes: [3, 7, 11, 13]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5], [1, 3, 5]]
  num_mels: 512
  upsample_initial_channel: 1024
  use_template: false
  pre_conv_kernel_size: 13
  post_conv_kernel_size: 13
