_target_: torch.nn.ModuleDict
modules:
  encoder:
    _target_: fish_vocoder.modules.encoders.convnext.ConvNeXtEncoder
    input_channels: "${eval: '${model.n_fft} // 2 + 1'}"
    depths: [6]
    dims: [512]
    drop_path_rate: 0.1
    kernel_sizes: [7]
  decoder:
    _target_: fish_vocoder.modules.generators.hifigan.HiFiGANGenerator
    hop_length: ${model.hop_length}
    upsample_rates: [8, 8, 4, 2, 2, 2]  # aka. strides
    upsample_kernel_sizes: [16, 16, 8, 4, 4, 4]
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
    num_mels: 512
    upsample_initial_channel: 512
    use_template: false
    pre_conv_kernel_size: 7
    post_conv_kernel_size: 7
