_target_: fish_vocoder.modules.generators.vocos.VocosGenerator
backbone:
  _target_: fish_vocoder.modules.generators.vocos.VocosBackbone
  input_channels: ${model.num_mels}
  depths: [3, 3, 27, 3]
  dims: [128, 256, 512, 1024]
  drop_path_rate: 0.4
  kernel_sizes: [7]
head:
  _target_: fish_vocoder.modules.generators.vocos.ISTFTHead
  dim: 1024
  n_fft: ${model.n_fft}
  hop_length: ${model.hop_length}
  padding: same
