defaults:
  - _self_
  - hydra: default
  - paths: default
  - trainer: default

task_name: refine
seed: 594461

base:
  sampling_rate: 44100
  num_mels: 128
  n_fft: 2048
  hop_length: 512
  win_length: 2048

data:
  _target_: fish_vocoder.data.datamodules.naive.NaiveDataModule
  batch_size: 16
  val_batch_size: 2
  num_workers: 2

  collate_fn:
    _target_: fish_vocoder.data.datasets.refine.collate_fn
    _partial_: true

  datasets:
    train:
      _target_: fish_vocoder.data.datasets.refine.AudioRefineDataset
      root: dataset/train
      base_transform:
        _target_: torch.nn.Sequential
        _args_:
          - _target_: fish_vocoder.data.transforms.hq_pitch_shift.RandomHQPitchShift
            probability: 1
            sampling_rate: ${base.sampling_rate}
          - _target_: fish_vocoder.data.transforms.crop.RandomCrop
            probability: 1
            crop_length: "${eval: '${base.hop_length} * 50'}"
      augment_transform:
        _target_: fish_vocoder.data.transforms.discontinuous.RandomDiscontinuous
        probability: 1
        sampling_rate: ${base.sampling_rate}

    val:
      _target_: fish_vocoder.data.datasets.refine.AudioRefineDataset
      root: dataset/valid
      base_transform:
        _target_: torch.nn.Sequential
        _args_:
          - _target_: fish_vocoder.data.transforms.crop.RandomCrop
            probability: 1
            crop_length: "${eval: '${base.hop_length} * 1000'}"
      augment_transform:
        _target_: fish_vocoder.data.transforms.discontinuous.RandomDiscontinuous
        probability: 1
        sampling_rate: ${base.sampling_rate}


model:
  _target_: torch.nn.ModuleDict
  modules:
    source_mel_transform:
      _target_: fish_vocoder.data.transforms.spectrogram.LogMelSpectrogram
      n_fft: ${base.n_fft}
      hop_length: ${base.hop_length}
      win_length: ${base.win_length}
      sample_rate: ${base.sampling_rate}
      n_mels: ${base.num_mels}
      f_min: 40
      f_max: 16000
    
    multi_scale_mel_transforms:
      _target_: torch.nn.ModuleList
      modules:
        - _target_: fish_vocoder.data.transforms.spectrogram.LogMelSpectrogram
          n_fft: ${base.n_fft}
          hop_length: ${base.hop_length}
          win_length: ${base.win_length}
          sample_rate: ${base.sampling_rate}
          n_mels: ${base.num_mels}
        - _target_: fish_vocoder.data.transforms.spectrogram.LogMelSpectrogram
          n_fft: 2048
          hop_length: 270
          win_length: 1080
          sample_rate: ${base.sampling_rate}
          n_mels: ${base.num_mels}
        - _target_: fish_vocoder.data.transforms.spectrogram.LogMelSpectrogram
          n_fft: 4096
          hop_length: 540
          win_length: 2160
          sample_rate: ${base.sampling_rate}
          n_mels: ${base.num_mels}

    # generator:
    #   _target_: fish_vocoder.modules.generators.refinegan.RefineGANGenerator
    #   sampling_rate: ${base.sampling_rate}
    #   hop_length: ${base.hop_length}
    #   downsample_rates: [2, 2, 2, 8, 8]
    #   upsample_rates: [8, 8, 2, 2, 2]
    #   leaky_relu_slope: 0.2
    #   num_mels: ${base.num_mels}
    #   start_channels: 16
    
    generator:
      _target_: fish_vocoder.modules.generators.hifigan.HiFiGANGenerator
      hop_length: ${base.hop_length}
      upsample_rates: [8, 8, 2, 2, 2]
      upsample_kernel_sizes: [16, 16, 8, 2, 2]
      resblock_kernel_sizes: [3, 7, 11]
      resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
      leaky_relu_slope: 0.2
      num_mels: ${base.num_mels}
      upsample_initial_channel: 512

    mpd:
      _target_: fish_vocoder.modules.discriminators.mpd.MultiPeriodDiscriminator
      periods: [3, 5, 7, 11, 17, 23, 37]
    
    mrd:
      _target_: fish_vocoder.modules.discriminators.mrd.MultiResolutionDiscriminator
      resolutions:
        - [1024, 120, 600]
        - [2048, 240, 1200]
        - [512, 50, 240]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2e-4
  betas: [0.8, 0.99]
  eps: 1e-6

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  _partial_: true
  gamma: 0.999

loop:
  log_interval: 50
  val_interval: 5000
  save_interval: 5000
  max_steps: 1000000
