defaults:
  - _self_
  - hydra: default
  - paths: default

task_name: refinegan_aug
seed: 42

global:
  sampling_rate: 44100
  num_mels: 128

data:
  _target_: fish_vocoder.data.datamodules.naive.NaiveDataModule
  batch_size: 16
  num_workers: 4

  datasets:
    train:
      _target_: fish_vocoder.data.datasets.refine.AudioRefineDataset
      root: dataset/train
      base_transform:
        _target_: torch.nn.Sequential
        _args_:
          - _target_: fish_vocoder.data.transforms.hq_pitch_shift.RandomHQPitchShift
            probability: 1
            sampling_rate: ${global.sampling_rate}
          - _target_: fish_vocoder.data.transforms.pad_crop.RandomPadCrop
            probability: 1
            crop_length: "${eval: '${global.sampling_rate} * 3'}"
            padding: true
      augment_transform:
        _target_: fish_vocoder.data.transforms.discontinuous.RandomDiscontinuous
        probability: 1
        sampling_rate: ${global.sampling_rate}
