_target_: lightning.Fabric
# need to convert primitive types, otherwise logger will not be list
_convert_: partial

accelerator: cuda
devices: auto
num_nodes: 1
strategy: ddp

# fp32 will be automatically cast into tf32 on compatible GPUs
precision: "32"

loggers:
  - _target_: lightning.fabric.loggers.TensorBoardLogger
    root_dir: ${paths.run_dir}/tensorboard/
    name: null
