_target_: fish_vocoder.models.hifigan.HiFiGANModel

sampling_rate: 44100
num_mels: 160
n_fft: 2048
hop_length: 512
win_length: 2048

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2e-4
  betas: [0.8, 0.99]
  eps: 1e-6

lr_scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR
  _partial_: true
  lr_lambda:
    _target_: fish_vocoder.schedulers.warmup_cosine.LambdaWarmUpCosineScheduler
    val_base: 2e-4
    val_final: 0
    max_decay_steps: ${trainer.max_steps}

mel_transforms:
  _target_: torch.nn.ModuleDict
  modules:
    input:
      _target_: fish_vocoder.data.transforms.spectrogram.LogMelSpectrogram
      n_fft: ${model.n_fft}
      hop_length: ${model.hop_length}
      win_length: ${model.win_length}
      sample_rate: ${model.sampling_rate}
      n_mels: ${model.num_mels}
      f_min: 40
      f_max: 16000

    loss:
      _target_: fish_vocoder.data.transforms.spectrogram.LogMelSpectrogram
      n_fft: ${model.n_fft}
      hop_length: ${model.hop_length}
      win_length: ${model.win_length}
      sample_rate: ${model.sampling_rate}
      n_mels: ${model.num_mels}

generator:
  _target_: fish_vocoder.modules.generators.hifigan.HiFiGANGenerator
  hop_length: ${model.hop_length}
  upsample_rates: [8, 8, 2, 2, 2]
  upsample_kernel_sizes: [16, 16, 8, 2, 2]
  resblock_kernel_sizes: [3, 7, 11]
  resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
  num_mels: ${model.num_mels}
  upsample_initial_channel: 512
  use_template: false

discriminators:
  _target_: torch.nn.ModuleDict
  modules:
    mpd:
      _target_: fish_vocoder.modules.discriminators.mpd.MultiPeriodDiscriminator
      periods: [3, 5, 7, 11, 17, 23, 37]

    mrd:
      _target_: fish_vocoder.modules.discriminators.mrd.MultiResolutionDiscriminator
      resolutions:
        - [1024, 120, 600]
        - [2048, 240, 1200]
        - [512, 50, 240]
